[package]
name = "haf-todo"
version = "0.1.0"
edition = "2021"

[dependencies]
layer9-core = { path = "../../crates/core", features = ["haf", "wasm"] }
wasm-bindgen = "0.2"
web-sys = "0.3"
console_error_panic_hook = "0.1"

[lib]
crate-type = ["cdylib"]
